### ISSUE TITLE
testing fixing of issue #412: missing scan www

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/django_zbp#415]
@fuzzylogic2000 I tested stage and it seems that the buttons work for all but three district. fir Tempelhof-Schöneberg, Spandau und FXB after clicking the buttons a new tab opens and then closes again.

**Comment by fuzzylogic2000** [comment]
The problem here is that all these links are pdfs. We cannot do anything about is as that is what the FIS broker gave us.

For example https://www.berlin.de/ba-friedrichshain-kreuzberg/politik-und-verwaltung/aemter/stadtentwicklungsamt/vermessung/abzeichnungen/0200001.pdf for Bplan 2 - 1

In my firefox, I get this window asking me to save:
![Screenshot from 2021-08-21 13-34-03](https://user-images.githubusercontent.com/8178179/130320503-90e3ad3a-1517-4a9e-a4b8-8536da3d9011.png)

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 ok now I get it. In firefox the window opens but in chrome the download starts automatically and I didn't see it. But do you know why in other districts the pdfs open in a new tab and for some as a download? Is that something we can influence?

**Comment by fuzzylogic2000** [comment]
We do currently put the `target="_blank"` on the link, so they should all open in a new tab. We can remove or keep that for all, I would say. All other districts have links to other files, not PDF, so they are opened and displayed in the other tab.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 I found a bplan with both the plan and the begründung opening as a pdf in a tab: http://mitte.gis-broker.de/bplaene/0102200d.pdf and https://fbinter.stadt-berlin.de//ScansBPlan/Begruendungen/0102200d_II-200d.pdf. What's the difference here to the link you found that leads to a download?

**Comment by fuzzylogic2000** [comment]
Can you add the ID of the bplan, so I can click the links? Doing that here opens both in the browser.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 II - 200d, Mitte

**Comment by goapunk** [comment]
I think the reason is that the first has the `content-disposition` header: 
```
content-disposition: attachment; filename="0200001.pdf"
```
which tells the browser to open it as attachment whereas the other files don't have it so they are opened inline.
